services:

  jekyll:
    build:
      context: ..
      dockerfile: docker/ruby/Dockerfile

    working_dir: /site

    volumes:
      - ..:/site

    ports:
      - "4004:4000"

    command: >
      bash -c "bundle install &&
      bundle exec jekyll serve --host 0.0.0.0 --livereload"